name:                fiscal-code
version:             0.1.0.0
synopsis:            Library to generate and verify the Italian fiscal code
description:         Library to generate and verify the Italian fiscal code
homepage:            https://github.com/marcosh/fiscal-code#readme
license:             OtherLicense
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2020 Marco Perone
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hourglass

library:
  source-dirs:       src
